name: Android CI

on: [ push ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: set up JDK 11
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Assembling app debug flavor
        run: ./gradlew :app:assembleDebug
      - name: run java unit and android tests
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: 29
          script: ./gradlew rootCoverageReport -Penable_android_test=true -Penable_unit_test=true -Pcoverage
      - name: upload code coverage report
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: false
