name: Android CI

on: [ push ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Assembling app debug flavor
        run: ./gradlew :app:assembleDebug
      - name: run java unit and android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew rootCoverageReport -Penable_android_test=true -Penable_unit_test=true -Pcoverage
      - name: upload code coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./build/reports/jacoco.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false
