name: Android CI

on: [ push ]

jobs:
  build:

    runs-on: macos-10.15
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Assembling app debug flavor
        run: ./gradlew :app:assembleDebug
      - name: run java unit tests
        run: ./gradlew clean rootCodeCoverageReport -Penable_android_test=true -Penable_unit_test=true -Pcoverage
      - name: upload code coverage report
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
